name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv pip install -e .
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --icon=icon.ico --name=epub-bilingual-translator-${{ runner.os }} book_nllb.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: epub-bilingual-translator-${{ runner.os }}
        path: dist/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          epub-bilingual-translator-Windows/*
          epub-bilingual-translator-Linux/*
          epub-bilingual-translator-macOS/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
